### ISSUE TITLE
Implement shell sort 

### ISSUE THREAD

**Issue by prityush9304** [prityush9304/Hacktoberfest-2021#56]
Apart from writing code, try to explain various complexities of this algo by giving suitable explanation

**Comment by Samikshahanchate** [comment]
please assgin me this issue to contribute.

**Comment by Samikshahanchate** [comment]
I have made PR for shell sort, please let me know if any changes needed

**Comment by Samikshahanchate** [comment]
Thank you.. Happy Coding :)
